
function c_read(name){var jar=document.cookie.split(';');var id=name+"=";var result="";for(var i=0;i<jar.length;i++){var c=jar[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(id)==0){result=c.substring(id.length,c.length);break;}}
if(result.length==0)result=":";return(result);}
function c_inc(c,pre){var re=new RegExp("(:"+pre+"([\\d]+):)");var result=re.exec(c);if(result==null){c+=pre+"1:";}else{re=new RegExp(result[1],"g");var r=":"+pre+(parseInt(result[2])+1).toString()+":";c=c.replace(re,r);}
return(c);}
function c_update(name,pre){if(pre!=""){var c=c_read(name);c=c_inc(c,pre);document.cookie=name+"="+c+"; SameSite=none; Secure; path=/; domain=.cooks.com;";}}
function switchfocus(){if(location.href.indexOf('#')==-1){if(document.topsearch.q){window.scrollTo(0,0);document.topsearch.q.focus();}}}
function ch(id){document.getElementById(id).style.display='none';}
function cs(id){document.getElementById(id).style.display='';}
function cooks_nl_submit(form){var email=form.email.value;if((email.length==0)||(email==null))return false;if(email.indexOf('@')==-1)return false;document.getElementById('cooks_newsletter').innerHTML='<B>Thanks for signing up!</B>';document.cookie="cooks_nl=:SUBMIT:; SameSite=Lax; Secure; path=/;";var posturl="https://ec.cooks.com/form204?w=cooks_newsletter&e="+escape(email);if(window.jQuery){$.ajax({type:"GET",url:posturl}).fail(function(){window.location.href=posturl;});}else{window.location.href=posturl;}
return false;}
function cooks_co_submit(form){var name=form.name.value;var email=form.email.value;var comment=form.comment.value;var url=form.url.value;var title=form.title.value;var parent=form.parent.value;var look=form.look.value;var rating=0;for(var i=0;i<form.rating.length;i++){if(form.rating[i].checked)
rating=form.rating[i].value;}
if((name.trim().length==0)||(name==null)){$(form.name).effect("pulsate",800);form.name.focus();return false;}
if((email.trim().length==0)||(email==null)||(email.indexOf('@')==-1)){$(form.email).effect("pulsate",800);form.email.focus();return false;}
if((comment.trim().length==0)||(comment==null)){$(form.comment).effect("pulsate",800);form.comment.focus();return false;}
if((url.length==0)||(url==null))return false;if((title.length==0)||(title==null))return false;ch('c_co_box');ch('c_co_f1');ch('c_co_f2');ch('c_co_f3');ch('c_co_f4');ch('c_co_f5');document.getElementById('c_co_msg').innerHTML='<B>Your comment has been sent.&nbsp; Thank you!</B>';localStorage.setItem('comment_name',name);localStorage.setItem('comment_email',email);var posturl="https://ec.cooks.com/form204?w=cooks_comment&n="+escape(name)+"&e="+escape(email)+"&r="+escape(rating)+"&c="+escape(comment)+"&u="+escape(url)+"&t="+escape(title)+"&p="+escape(parent);if(window.jQuery){$.ajax({type:"GET",url:posturl}).fail(function(){window.location.href=posturl;});$('#c_co_box').show("fade",800);}else{window.location.href=posturl;cs('c_co_box');}
if(look.length>0)document.getElementById(look).scrollIntoView();return false;}
function cooks_co_cradio(form,select,focus){if(form==null||form=="")form=document.commentform;select=parseInt(select);if(focus==null||focus=="")focus=true;form.rating[select].checked=true;if(window.jQuery){for(var i=0;i<form.rating.length;i++){if(form.rating[i].checked)
$(form.rating[i]).parent().css({backgroundColor:'#EBEEE5',borderBottomColor:'#FFC04E'});else
$(form.rating[i]).parent().css({backgroundColor:'',borderBottomColor:''});}}
if(focus){if(form.name.value.trim().length==0)form.name.focus();else if(form.email.value.trim().length==0)form.email.focus();else if(form.comment.value.trim().length==0)form.comment.focus();}}
function cooks_co_reset(form,parent,look){if(parent==null)parent=0;form.parent.value=parent;form.look.value=look;form.comment.value="";cooks_co_cradio(form,0,false);cs('c_co_f1');cs('c_co_f2');cs('c_co_f3');cs('c_co_f4');cs('c_co_f5');document.getElementById('c_co_msg').innerHTML='';var savedName=localStorage.getItem('comment_name');var savedEmail=localStorage.getItem('comment_email');if(savedName){form.name.value=savedName;}
if(savedEmail){form.email.value=savedEmail;}}
function cooks_co_comment(form,parent,who,look){var message='<DIV STYLE="position: relative;">';message+='<DIV STYLE="position: absolute; right: 0;"><A HREF="#" onclick="ch(\'c_co_box\'); return false;"><svg viewBox="0 0 12 16" version="1.1" aria-hidden="true" class="sbutton option-h" style="fill: #666;"><path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48L7.48 8z"></path></svg></A></DIV>';if(form==null||form=="")form=document.commentform;if(parent==null)parent=0;if(who==null)who="";if(look==null)look="";if(form.title.value.length>2){message+='<SPAN CLASS="subscript"><B>~ '+form.title.value+' ~</B></SPAN><BR>';}
parent=parseInt(parent);ch('c_co_box');cooks_co_reset(form,parent,look);if(who.length>0){message+="<B>Reply to <I>"+who+"</I></B>";}else if(parent>0){message+="<B>Reply to review # <I>"+parent+"</I></B>";}else{message+="<B>Add review or comment</B>";}
message+="</DIV>";document.getElementById('c_co_msg').innerHTML=message;var source=document.getElementById('c_co_box');var dest=document.getElementById('co'+parent+'r');dest.parentNode.insertBefore(source,dest.nextSibling);if(window.jQuery){$('#c_co_box').show("fade",800);}else{cs('c_co_box');}
if(look.length>0)document.getElementById(look).scrollIntoView();if(form.name.value.trim().length==0)form.name.focus();else if(form.email.value.trim().length==0)form.email.focus();else if(form.comment)form.comment.focus();}
function cooks_co_events(){$('[name=commentform]').on('keydown','input',function(event){if(event.which==13){event.preventDefault();var $this=$(event.target);var index=parseInt($this.attr('data-index'));if(index>0){var next=$('[data-index="'+(index+1)+'"]');if(next.length)next.focus();}
return false;}});if(!('ontouchstart'in document.documentElement)){var ctstatus=true;$('#c_co_ctaction, #c_co_ctaction2, #c_co_rating, #c_co_rating2, #c_co_rating3').each(function(){var ctout;var $this=$(this);$this.hover(function(event){event.preventDefault();ctout=setTimeout(function(){$this.off('mouseenter mouseleave');if(ctstatus){if(!$('#c_co_box').is(':visible')){cooks_co_comment('',0,'','c_co_ctaction');}
ctstatus=false;}},1500);return false;},function(event){event.preventDefault();clearTimeout(ctout);return false;});});}}
function cooks_em_validate(event){var tosubmit=true;var email=document.emailform.post_mail.value;if((email.trim().length<6)||(email==null))tosubmit=false;if(email.indexOf('@')==-1)tosubmit=false;if(tosubmit==false){if(window.jQuery)$(document.emailform.post_mail).effect("pulsate",800);event.preventDefault();return false;}
ch('emailformbutton1');document.getElementById('emailformbutton2').style.display='inline-block';return true;}
function cooks_txt_replace(element,value){if(element.selectionStart||element.selectionStart=='0'){var start=element.selectionStart;var end=element.selectionEnd;before=(element.value).substring(0,start);sel=(element.value).substring(start,end);after=(element.value).substring(end,element.textLength);prevTop=element.scrollTop;element.value=before+value+after;element.selectionStart=start+value.length;element.selectionEnd=element.selectionStart;element.focus();element.scrollTop=prevTop;}}
function cooks_clipfromid(id,option){if((option=="blur")&&window.jQuery){var tt=$("#linkcopy");tt.css({backgroundColor:'#D8E8D8'}).delay(200);tt.animate({backgroundColor:'#F8FBF2'},200);tt.animate({backgroundColor:'#D8E8D8'},200);tt.animate({backgroundColor:'#F8FBF2'},{duration:200,complete:function(){$(this).css({backgroundColor:''});}});}
var field=document.getElementById(id);if(field){field.focus();field.selectionStart=0;field.selectionEnd=field.value.length;if(!navigator.clipboard){document.execCommand('copy');}else{navigator.clipboard.writeText(field.value);}
if(option=="blur")field.blur();}
return false;}
function cooks_rc_submit(form){form.action="/rec"+form.sf.value;form.sf.selectedIndex=0;form.submit();}
function cooks_var(){cooks_var.storage=true;}
if(window.jQuery){$(function(){var csfblock_pos=$('#aftercsf').offset().top;cooks_var.bar_type=(cooks_var.bar_type===undefined)?0:cooks_var.bar_type;cooks_var.bar_oldpos=0;cooks_var.bar_status=false;cooks_var.bar_delay_up=0;cooks_var.bar_delay_down=0;window.addEventListener('scroll',function(e){var csfblock_newpos=$(this).scrollTop();if(csfblock_newpos<cooks_var.bar_oldpos){cooks_var.bar_delay_up++;cooks_var.bar_delay_down=0;}
if(csfblock_newpos>cooks_var.bar_oldpos){cooks_var.bar_delay_up=0;cooks_var.bar_delay_down++;}
if(cooks_var.bar_type==1){if(csfblock_newpos<csfblock_pos){if(cooks_var.bar_status==true){$('#csfblock').slideUp(250);cooks_var.bar_status=false;}}else if(cooks_var.bar_status==true&&cooks_var.bar_delay_down>1){$('#csfblock').slideUp(250);cooks_var.bar_status=false;}else if(cooks_var.bar_status==false&&cooks_var.bar_delay_up>1){$('#csfblock').slideDown(250);cooks_var.bar_status=true;}}else if(cooks_var.bar_type==2){if(csfblock_newpos<csfblock_pos){if(cooks_var.bar_status==true){$('#csfblock').slideUp(250);cooks_var.bar_status=false;}}else if(cooks_var.bar_status==false&&cooks_var.bar_delay_down>1){$('#csfblock').slideDown(250);cooks_var.bar_status=true;}else if(cooks_var.bar_status==false&&cooks_var.bar_delay_up>1){$('#csfblock').slideDown(250);cooks_var.bar_status=true;}}
cooks_var.bar_oldpos=csfblock_newpos;if(cooks_var.related_enable==true){var pos=0;if($('#related-main').length)pos=$('#related-main').offset().top;if((pos>0)&&window.jQuery.ui){if(csfblock_newpos+$(window).height()>pos){cooks_var.related_enable=false;var tt=$("#related-first");if(tt.length){if(tt.is("[data-tt-rating]")){setTimeout(function(){tt.trigger("mouseover");},1000);setTimeout(function(){tt.trigger("mouseleave");},6000);}else{cooks_var.related_more_enable=true;}}else{cooks_var.related_more_enable=true;}}}}
if(cooks_var.poplist_enable==true){var pos=0;if($('#poplist-main').length)pos=$('#poplist-main').offset().top;if((pos>0)&&window.jQuery.ui){if(csfblock_newpos+$(window).height()>pos){cooks_var.poplist_enable=false;var tt=$("#poplist-first");if(tt.length){setTimeout(function(){tt.trigger("mouseover");},1000);setTimeout(function(){tt.trigger("mouseleave");},6000);}}}}
if(cooks_var.related_more_enable==true){var pos=0;var tt=$("#related-more");if(tt.length)pos=tt.offset().top;if((pos>0)&&window.jQuery.ui){if(csfblock_newpos+$(window).height()>pos){cooks_var.related_more_enable=false;setTimeout(function(){tt.animate({borderLeftWidth:'0.2rem',borderRightWidth:'0.2rem'},225);tt.animate({borderColor:'#E4CCA7'},250);tt.animate({backgroundColor:'#FFE'},30);tt.animate({borderColor:'#F8E0BB'},250);tt.animate({backgroundColor:'#FDFDCB'},30);tt.animate({borderLeftWidth:1,borderRightWidth:1},{duration:225,complete:function(){$(this).css({backgroundColor:''});}});},1000);}}}},{passive:true});});if(window.jQuery.ui){$(function(){$("#topsearch3-q, #topsearch2-q").autocomplete({source:"https://ec.cooks.com/autocomplete",minLength:1,delay:200,select:function(event,ui){if(ui.item){$(event.target).val(ui.item.value);}
$(event.target.form).submit();}});});$(function(){if(cooks_var.tooltip_enable==true){var tooltips=$("A[data-tt-title]").tooltip({position:{at:"right+20 top-30",collision:"fit none"},show:{effect:"fade",delay:500},hide:false,items:"A[data-tt-title], A[data-tt-rating], A[data-tt-review]",content:function(){var string="";var element=$(this);if(element.is("[data-tt-title]")){var title=element.attr("data-tt-title");string+='<SPAN CLASS="subscript"><B>'+title+'</B></SPAN><BR>';}
if(element.is("[data-tt-rating]")){var rating=element.attr("data-tt-rating");string+='<SPAN class="rating-static rating-'+rating+'"></SPAN>';}
if(element.is("[data-tt-review]")){var isplural="";var review=element.attr("data-tt-review");if(review>1)isplural="s";if(string.length>0)string+=" ";string+='<SPAN CLASS="navigation"><B>'+review+'</B>&nbsp;review'+isplural+'</SPAN>';}
if(string.length>0)return string;},close:function(){$("[role=log].ui-helper-hidden-accessible").remove();}});$("[role=log].ui-helper-hidden-accessible").remove();}});}}